export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"项目主页","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"t":"幻灯片页","i":"slides"},["/slides","/slides.md"]],
  ["v-1473bf53","/demo/",{"t":"主要功能与配置演示","i":"discover"},["/demo/index.html","/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"t":"布局与功能禁用","i":"config"},["/demo/disable","/demo/disable.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"t":"密码加密的文章","i":"lock"},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-438ffe52","/demo/markdown.html",{"t":"Markdown 展示","i":"markdown"},["/demo/markdown","/demo/markdown.md"]],
  ["v-6e19edb7","/demo/page.html",{"t":"页面配置","i":"page"},["/demo/page","/demo/page.md"]],
  ["v-2d0a870d","/en/",{"t":"Project home","i":"home"},["/en/index.html","/en/README.md"]],
  ["v-367b840a","/en/slides.html",{"t":"Slide page","i":"slides"},["/en/slides","/en/slides.md"]],
  ["v-fffb8e28","/guide/",{"t":"指南","i":"creative"},["/guide/index.html","/guide/README.md"]],
  ["v-395cd082","/en/demo/",{"t":"Features Demo","i":"discover"},["/en/demo/index.html","/en/demo/README.md"]],
  ["v-70eda030","/en/demo/disable.html",{"t":"Disabling layout and features","i":"config"},["/en/demo/disable","/en/demo/disable.md"]],
  ["v-3777b6d3","/en/demo/encrypt.html",{"t":"Encryption Article","i":"lock"},["/en/demo/encrypt","/en/demo/encrypt.md"]],
  ["v-4a2a37eb","/en/demo/markdown.html",{"t":"Markdown Enhance","i":"markdown"},["/en/demo/markdown","/en/demo/markdown.md"]],
  ["v-0e4acecb","/en/demo/page.html",{"t":"Page Config","i":"page"},["/en/demo/page","/en/demo/page.md"]],
  ["v-e6412400","/en/guide/",{"t":"Guide","i":"creative"},["/en/guide/index.html","/en/guide/README.md"]],
  ["v-5d5c2d30","/guide/bar/",{"t":"Bar 功能","i":"creative"},["/guide/bar/index.html","/guide/bar/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"t":"Baz","i":"info"},["/guide/bar/baz","/guide/bar/baz.md"]],
  ["v-5d5821d6","/guide/foo/",{"t":"Foo 功能","i":"config"},["/guide/foo/index.html","/guide/foo/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"t":"Ray","i":"config"},["/guide/foo/ray","/guide/foo/ray.md"]],
  ["v-13a6747c","/en/guide/bar/",{"t":"Bar feature","i":"creative"},["/en/guide/bar/index.html","/en/guide/bar/README.md"]],
  ["v-f91f53cc","/en/guide/bar/baz.html",{"t":"Baz","i":"info"},["/en/guide/bar/baz","/en/guide/bar/baz.md"]],
  ["v-13a87a29","/en/guide/foo/",{"t":"Foo feature","i":"config"},["/en/guide/foo/index.html","/en/guide/foo/README.md"]],
  ["v-663a5418","/en/guide/foo/ray.html",{"t":"Ray","i":"config"},["/en/guide/foo/ray","/en/guide/foo/ray.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
